import express from 'express';
const router = express.Router();
import systemConTroller from '@/controllers/systemController';
import asyncHandler from '@/core/errorHandler';
import verifyToken from '@/middlewares/verifyToken';
import checkAdmin from '@/middlewares/checkAdmin';

router.use(asyncHandler(verifyToken));
router.use(asyncHandler(checkAdmin));
router.post('/add-menu', asyncHandler(systemConTroller.addMenu));
router.post('/edit-menu', asyncHandler(systemConTroller.editMenu));
router.get('/get-menus', asyncHandler(systemConTroller.getMenus));
router.get('/get-parent-menus', asyncHandler(systemConTroller.getParentMenus));
router.get('/get-menu-tree', asyncHandler(systemConTroller.getMenuTree));
router.post('/add-unit', asyncHandler(systemConTroller.addUnit));
router.get('/get-unit-list', asyncHandler(systemConTroller.getUnitList));
router.post('/edit-unit', asyncHandler(systemConTroller.editUnit));
router.post('/delete-unit', asyncHandler(systemConTroller.deleteUnit));
router.post('/add-company', asyncHandler(systemConTroller.addCompany));
router.get('/get-companies', asyncHandler(systemConTroller.getCompanies));
router.post('/edit-company', asyncHandler(systemConTroller.editCompany));
router.post('/delete-company', asyncHandler(systemConTroller.deleteCompany));
router.get('/get-distributors', asyncHandler(systemConTroller.getDistributors));
router.post('/add-distributor', asyncHandler(systemConTroller.addDistributor));
router.post('/edit-distributor', asyncHandler(systemConTroller.editDistributor));
router.post('/delete-distributor', asyncHandler(systemConTroller.deleteDistributor));
router.post('/add-type', asyncHandler(systemConTroller.addType));
router.post('/get-types', asyncHandler(systemConTroller.getTypes));
router.post('/edit-type', asyncHandler(systemConTroller.editType)); 
router.get('/get-types-tree', asyncHandler(systemConTroller.getTypesTree));
router.post('/delete-type', asyncHandler(systemConTroller.deleteType));
export default router;